version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  ansible-lint:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-lint

  run-ansible:
    working_directory: /tmp/ansible
    executor:
      docker: true
    steps:
    - checkout
    - ansible-playbook/playbook:
        playbook: apache-server.yml
    - run:
        name: Validation of deployed Apache Server
        command: |
          curl http://localhost/index.html

workflows:
  ansible-using-orbs:
    jobs:
      - ansible-lint
      - run-ansible:
          requires:
            - ansible-lint
