version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3
  slack: circleci/slack@4.2.0

jobs:
  ansible-lint:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-lint

  run-ansible:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-playbook
    - run:
        name: Validation of deployed Apache Server
        command: |
          curl http://localhost/index.html
    - slack/notify:          
          event: pass
          template: basic_fail_1
          mentions: "<@Elon Bar-Evan>"

  notify-using-custom-notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Apache Server Deployed successfully*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  ansible-using-orbs:
    jobs:
      - ansible-lint
      - slack/on-hold:
          context: slack-secrets
          requires:
            - ansible-lint
      - pause_workflow:
          requires:
            - ansible-lint
            - slack/on-hold
          type: approval
      - run-ansible:
          requires:
            - ansible-lint
            - pause_workflow
      - notify-using-custom-notify:
          requires:
            - run-ansible
            - pause_workflow
          context: slack-secrets
