version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  run-ansible:
    working_directory: /tmp/ansible
    executor:
      name: ansible-playbook/default
      python-version: "3.6.3"
      #debian-release: "rc"
    steps:
    - checkout
    - run: sudo apt-get update -y && sudo apt-get install -y python-apt
    - ansible-playbook/install:
        version: "2.7.4"
    - run: sudo pip list
    - ansible-playbook/playbook:
        playbook: apache-server.yml
    - run:
        name: Validation of deployed Apache Server
        command: |
          curl http://localhost/index.html

workflows:
  ansible-using-orbs:
    jobs:
      #- ansible-lint
      - run-ansible

