version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3
  slack: circleci/slack@4.2.0

jobs:
  ansible-lint:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-lint

  run-ansible:
    machine: true
    steps:
    - add_ssh_keys:
          fingerprints:
            - "b6:6c:11:1f:a3:ee:dd:a4:e3:d6:0e:99:e8:fe:ba:b9"
    - checkout   

workflows:
  ansible-using-orbs:
    jobs:
      - ansible-lint
      - slack/on-hold:
          context: slack-secrets
          mentions: "@elon"
          requires:
            - ansible-lint
      - pause_for_approval:
          requires:
            - ansible-lint
            - slack/on-hold
          type: approval
      - run-ansible:
          requires:
            - ansible-lint
            - pause_for_approval
          context: slack-secrets
      - run-intergration-tests:
          requires:
            - ansible-lint
            - run-ansible
          context: slack-secrets
