version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3
  
jobs:
  run-ansible:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - run:
        name: Create Index html file
        command: |          
          echo "TechnoTrainer testing" >> /etc/ansible/index.html         
    - ansible/ansible-lint
    - ansible/ansible-playbook
    - run:
        name: Hit Apache URL
        command: |
          whoami
          curl http://localhost/index.html

workflows:
  ansible-using-orbs:
    jobs:
      #- ansible/show-os-version
      - run-ansible # checkout, build, test, and upload test results
          