version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3
  
jobs:
  run-ansible:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - add_ssh_keys:
          fingerprints:
            - "27:b1:27:8e:b3:1a:b4:5f:3d:f1:41:a3:f9:97:75:b7"
    - run:
           name: Deploy Over SSH
           command: |
             ssh -vvv -o StrictHostKeyChecking=no ec2-user@18.218.164.148 "hostname"
    - checkout
    - run:
        name: Create Index html file
        command: |          
          echo "TechnoTrainer testing" >> /etc/ansible/index.html         
    - ansible/ansible-playbook
    - run:
        name: Hit Apache URL
        command: |
          whoami
          curl http://localhost/index.html

workflows:
  ansible-using-orbs:
    jobs:
      #- ansible/show-os-version
      - run-ansible # checkout, build, test, and upload test results
          