version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3

jobs:
  ansible-lint:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-lint

workflows:
  ansible-using-orbs:
    jobs:
      - ansible-lint
