version: 2.1

orbs:
  ansible: orbss/ansible@0.2.3

jobs:
  ansible-lint:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-lint

  run-ansible:
    working_directory: /tmp/ansible
    executor:
      name: ansible/ubuntu18-ansible-apt
    steps:
    - checkout
    - ansible/ansible-playbook
    - run:
        name: Validation of deployed Apache Server
        command: |
          curl http://localhost/index.html

workflows:
  ansible-using-orbs:
    jobs:
      - ansible-lint
      - run-ansible:
          requires:
            - ansible-lint
